on:
  workflow_dispatch:

env:
  CI: 1
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sh scripts/docker/build.sh ${{ github.event.inputs.dockerTag }}
